version: 2.1

# orbs:
#    spellcheck: circleci/spellcheck@1.2.0
  #  slack: circleci/slack@1.2.0
   
# commands:
#   slack-notify-on-failure:
#     steps:
#       -slack/status:
#         fail_only = "true"
        # only_for_branch: "master"

workflows:
  ci:
    jobs:
      - build
      # - test
   
jobs:
  build:
    docker:
      # using a base image 
      - image: cimg/base:stable
    steps:
      - checkout
  
  test: 
    - run:
      name: Run Tests
      command:
        - run test.js

      - setup_remote_docker:
        docker_layer_caching: true
      