version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv helloworld
            . helloworld/bin/activate
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            . helloworld/bin/activate